### ISSUE TITLE
Adding dependency list for kfk compilation - or configure file

### ISSUE THREAD

**Issue by bouviervj** [KxSystems/kafka#10]
We need to install libs before compilation.
On blank VM AWS EC2 - Ubuntu 18 64Bits 

libz-dev
libssl-dev

Are missing at compile time.

**Comment by sv** [comment]
This is noted in https://github.com/KxSystems/kafka#requirements section in README. librdkafka updated their list recently as well, so maybe it is better to refer to their list without duplicating it
