### ISSUE TITLE
Bad config can cause consumer not to get data

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/kafka#101]
Recreation 

Run test_consumer.q and subscribe to data. Now quit & edit test_consumer.q to have an extra config 
```(`queue.buffering.max.ms;`1);```

you will get no data & when exit you will see
```"(4i;\"CONFWARN\";\"[thrd:app]: Configuration property queue.buffering.max.ms is a producer property and will be ignored by this consumer instance\")"```

**Comment by sshanks-kx** [comment]
This needs to be a 'valid' param, but incorrect in the context.

If I add a param of ```(`rubbish;`1);``` it immediately errors with ..```'No such configuration property: "rubbish"```...and has a different reaction.

Appears that this param passes local validation (hence the Client creation call doesnt fail), but flagged later from the remote connection.

**Comment by sshanks-kx** [comment]
Temp adding the following after creating the consumer client allows it to work
.kfk.Poll[client;1;1];
Looking at automatically polling after creating client in order to get log message immediately & why it isnt polling there normally.

**Comment by davidcrossey** [comment]
This parameter also appears to affect producers if present, from receiving call backs in conjunction with ```(`acks;`1)```

**Comment by sshanks-kx** [comment]
fixed in #102
