### ISSUE TITLE
Kfk.sub

### ISSUE THREAD

**Issue by chunaiarun** [KxSystems/kafka#103]
Whether consumer can subscribe at topic level without specifying the partition? If so can you provide me an example

if partition should be always specified always , how should I specify 

I was trying to specific subscriptions with callback function
.kfk.Subcribe[client;`topic1;`id`err`leader`replicas`isrs!(0i;`Success;0i;0 1 2i;2 1 0i);callbck] here partition is dictionary. It is not working. Whether as my python code is working at topic level.

help needed

**Comment by sshanks-kx** [comment]
See 
https://github.com/KxSystems/kafka/blob/master/examples/test_consumer.q
Thanks

**Comment by chunaiarun** [comment]
Thank you. When I use enlist .kfx.PARTITION_UA 
I get return value as UNKNOWN topic or PARTITION

**Comment by chunaiarun** [comment]
If partition is 0 1 and 2 , how to specific it in .kfx.subscribe function

**Comment by sshanks-kx** [comment]
You use `assign` instead of `subscribe` if you dont want automatic assignment ,https://github.com/KxSystems/kafka/blob/master/docs/reference.md#assign
Please also ensure using latest release.

**Comment by sshanks-kx** [comment]
FYI: Ive noticed #105 which may (or may not) be related to what you saw originally.

**Comment by chunaiarun** [comment]
Working fine
