### ISSUE TITLE
Hardcoded value for message recovery

### ISSUE THREAD

**Issue by jonnypress** [KxSystems/kafka#11]
I think this line: 
https://github.com/KxSystems/kafka/blob/master/kfk.c#L430
restricts the consumer to recovering a maximum of 10k messages upon recovery.  Is that correct, or am I doing something wrong? If correct, is there a reason? Can it be made configurable?

Thanks!

**Comment by sv** [comment]
maxcnt will not be used once https://github.com/KxSystems/kafka/pull/13 is merged.
