### ISSUE TITLE
Flexible location for kafka lib 

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/kafka#24]
Makefile has

```
KAFKA_ROOT     = ${HOME}
KFK_INCLUDE    = ${KAFKA_ROOT}/include
```

When building, its looking for Kafka libs in home dir. 
Could add change to make it more flexible and allow it to use a Kafka lib installed anywhere.
Also need to update README to inform uses that they can use this in order to build/etc

**Comment by cmccarthy1** [comment]
This was resolved in PR #25
