### ISSUE TITLE
Thread starvation when consuming persisted messages

### ISSUE THREAD

**Issue by cmccarthy1** [KxSystems/kafka#37]
**Client Raised Issue**

**Describe the bug**
When consuming persisted data with large numbers of messages, thread starvation can occur as the main thread is blocked until consumption is completed.

**To Reproduce**
- Create a Kafka topic with say few hundred thousand messages persisted. This will create q main thread starvation.
- Set consumer to read from the begining -> (`auto.offset.reset;`earliest);
- make group_id random string. It has to be unique string. We do not use consumer groups in many use cases so random is fine.

Settings:
```
group_id:20?.Q.a
kfk_cfg:(!) . flip(
    (`metadata.broker.list;`localhost:9100);  
    (`group.id;group_id);
    (`statistics.interval.ms;`10000);
    (`enable.auto.commit;`false);
    (`auto.offset.reset;`earliest);
    (`queue.buffering.max.ms;`1);
    (`fetch.wait.max.ms;`10)
    );
```

**Expected behavior**
There should be a mechanism by which to interrupt the consumption process or an option to allow this consumption to take place in a more controlled manner.

**Comment by sshanks-kx** [comment]
Issue recreated

**Comment by sshanks-kx** [comment]
Ref: consumer configs, which also relate to how much data consumed 
https://kafka.apache.org/08/documentation.html#consumerconfigs

**Comment by sshanks-kx** [comment]
-191 msgtype can appear when reaches current end of offset (_PARTITION_EOF appears as mtype in 'data' table)
https://github.com/confluentinc/confluent-kafka-python/issues/283

Have initial version of reads-per-chance to prevent thread starvation … testing ...
