### ISSUE TITLE
Modify `.kfk.consumecb` functionality to allow per topic/client pair granularity

### ISSUE THREAD

**Issue by cmccarthy1** [KxSystems/kafka#54]
**Internally raised issue**

**Is your feature request related to a problem? Please describe.**
The addition of support for consumption on a per topic basis in #47 allows consumption to be managed based on topic. Consumption can occur from the same topic name but different clients

**Describe the solution you'd like**
Potentially key the topic specific callback logic to a multi key lookup allowing flexibility on what granularity the callbacks can handle various callbacks can be invoked.

**Describe alternatives you've considered**
It is possible for a user within the functions specific to the topic to add per client logic as applicable. This issue should as such be seen as a potential enhancement with the caveat that a lookup on the topic consumption across 2 keys may eat in too heavily to the consumecb function to allow it to be scalable

**Additional resource**
No additional resources available for this issue at this time. Further resourcing will be provided in comments if necessary

**Comment by mshimizu-kx** [comment]
This was included in kafkakdbv2.0 as .kafka.registerConcumeTopicCallback.
