### ISSUE TITLE
Deleting a client and recreating it causes segfault

### ISSUE THREAD

**Issue by rpoply1** [KxSystems/kafka#61]
Looks like .kfk.ClientDel is not cleaning up resources properly. Deleting a client and then recreating one with the same config results in a segfault. Please see below for a reproducible case. 

```
\l kfk.q
\c 20 200

kfk_cfg:(!) . flip(
    (`metadata.broker.list;`172.31.1.104:9011);
    (`group.id;`0)
    );

client1: .kfk.Consumer kfk_cfg;
.kfk.Sub[client1;`foo; enlist .kfk.PARTITION_UA];

system "sleep 2";
.kfk.Unsub client1;
.kfk.ClientDel client1;

client2: .kfk.Consumer kfk_cfg;
```

**Comment by cmccarthy1** [comment]
Hi @rpoply1,

I've updated the main branch to fix this issue, I had been able to replicate the issue above and the fix by checking that the clients are not `(S)0` i.e. set to null. Please check this is sufficient and reopen as appropriate if there are any issues.

**Comment by rpoply1** [comment]
Hi @cmccarthy1, thanks for the quick fix, I appreciate it. I will give that a go and let you know if I run into any issues.
