### ISSUE TITLE
q process can hang on exit if kafka topic/client is not cleaned up

### ISSUE THREAD

**Issue by rpoply1** [KxSystems/kafka#65]
Creating multiple clients and topics with the same config can cause the q process to hang if the topic is not cleaned up before exit. 

Here is a reproducible case:
```
\l kfk.q
producer1: .kfk.Producer[enlist[`metadata.broker.list]!enlist `172.30.4.232:9010];
topic1: .kfk.Topic[producer1;`test;()!()];
.kfk.ClientDel producer1;

producer2: .kfk.Producer[enlist[`metadata.broker.list]!enlist `172.30.4.232:9010];
.kfk.Topic[producer2;`test;()!()];
.kfk.Topic[producer2;`test;()!()];
```
Try exiting the process after running this script

**Comment by cmccarthy1** [comment]
Issue is related to topics associated with clients not being deleted when a client is deleted. A fix for this is currently being looked at
