### ISSUE TITLE
SASL/Kerberos authentication 

### ISSUE THREAD

**Issue by BogdanS** [KxSystems/kafka#75]
I am looking to connect to a topic that requires SASL authentication.
Would I be able to do this using this library? if yes, what would an example look like?
Thank you

**Comment by cmccarthy1** [comment]
This currently isn't supported within the interface. It would require a number of additional functions to be exposed from the underlying C api, by the look of things it should be feasible to add. We'll look into this in the New Year

**Comment by BogdanS** [comment]
Thank you for the quick reply!
Are you referring by any chance to the publisher api or the client api as well?
I.e. would I not be able to consume an already existing kafka topic that requires SASL authentication just by setting the appropriate client config flags? (adding `sasl.kerberos.keytab, etc. to the client's kfk_cfg dictionary )

**Comment by mshimizu-kx** [comment]
Hi Bogdan,

As far as I see we are passing a q configuration dictionary without filtering its keys when creating a client (both producer and consumer). rdkafka has already had SASL authentication functionality/ So as you said,  I guess this is realized by a configuration setting.

For your reference:
- https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
- https://docs.confluent.io/platform/current/security/security_tutorial.html

Note: Our installation instruction is disabling SASL at the build of rdkafka from the source (`--disable-sasl` flag after `configure`).

Thanks

**Comment by mshimizu-kx** [comment]
Looks like the setting change did the job.
