### ISSUE TITLE
Getting error when trying to load kfk.q

### ISSUE THREAD

**Issue by wlee-git-sys** [KxSystems/kafka#84]
**Describe the bug**
Installed kdb kafka on WIndows using WSL and Ubuntu - everything looked ok.  When running q and using the load command
\l kfk.q

I get the following error
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
w32/ 8()core 4095MB wlee use7410wlee2 192.168.1.196 NONEXPIRE

Welcome to kdb+ 32bit edition
For support please see http://groups.google.com/d/forum/personal-kdbplus
Tutorials can be found at http://code.kx.com
To exit, type \\
To remove this startup msg, edit q.q
q)\l kfk.q
'The specified module could not be found.
  [2]  \\wsl$\Ubuntu-20.04\home\wlee\kdb_kafka\kfk.q:74: .kfk,:(`$3_'string funcs[;0])!LIBPATH@/:funcs
                                                                                               ^
  [0]  (<load>)

**Expected behavior**
don't expect error

**Screenshots**

**Desktop (please complete the following information):**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

APologies, new to KDB and Kafka - but I would have expected this to work out of the box.  Any help would be appreciated.

**Comment by cmccarthy1** [comment]
Although this won't be the underlying issue this interface isn't supported for 32bit versions of kdb+. You can install an on-demand licence [here](https://ondemand.kx.com/) which will be more suitable.

Can you please outline what instructions/steps you followed in order to install the interface? The interface won't work 'out of the box', rather it will need you to install following the instructions outlined [here](https://github.com/KxSystems/kafka#linux--mac)

**Comment by wlee-git-sys** [comment]
HI, 

Thank you for the response - apologies - when I said out of the box - those instructions are what I meant :-) I followed them, compiled the version on Ubuntu as per the instructions and then got the error .  

The specific error doesn't look like a bad installation or 32 vs 64bit version - but more of a missing library path or library:

    On Saturday, June 5, 2021, 10:12:41 AM EDT, cmccarthy1 ***@***.***> wrote:  
 
 


Although this won't be the underlying issue this interface isn't supported for 32bit versions of kdb+. You can install an on-demand licence here which will be more suitable.

Can you please outline what instructions/steps you followed in order to install the interface? The interface won't work 'out of the box', rather it will need you to install following the instructions outlined here

**Comment by wlee-git-sys** [comment]
Apologies email got cut off.  As I said, it looks like more of a missing library path or library
'The specified module could not be found.
[2] \wsl$\Ubuntu-20.04\home\wlee\kdb_kafka\kfk.q:74: .kfk,:(`$3_'string funcs[;0])!LIBPATH@/:funcs
Could you confirm where these functions should be loaded from?
Thanks!
    On Saturday, June 5, 2021, 10:32:09 AM EDT, Wei-Wen Lee ***@***.***> wrote:  
 
  HI, 

Thank you for the response - apologies - when I said out of the box - those instructions are what I meant :-) I followed them, compiled the version on Ubuntu as per the instructions and then got the error .  

The specific error doesn't look like a bad installation or 32 vs 64bit version - but more of a missing library path or library:

    On Saturday, June 5, 2021, 10:12:41 AM EDT, cmccarthy1 ***@***.***> wrote:  
 
 


Although this won't be the underlying issue this interface isn't supported for 32bit versions of kdb+. You can install an on-demand licence here which will be more suitable.

Can you please outline what instructions/steps you followed in order to install the interface? The interface won't work 'out of the box', rather it will need you to install following the instructions outlined here

**Comment by cmccarthy1** [comment]
The missing library is probably a result of the 32 vs 64 bit difference, in order for q to pick up the library it needs to have the appropriate shared object within `$QHOME/[l|w|m][32|64]`

Can you return the output from
```
ls $QHOME/
```
the output from running `ls` on the `l64`/`l32` directory that exists within `$QHOME`

**Comment by cmccarthy1** [comment]
If this is still an issue please reopen with additional information. Closing for now

**Comment by wlee-git-sys** [comment]
Thank you for all your help! Apologies for not getting back earlier as other items required my attention.  I am planning to get back into it the next couple of days, if I run into the same issues, should I open a new request as indicated above or just respond to this email chain?
Regards,
    On Monday, June 21, 2021, 04:13:15 AM EDT, cmccarthy1 ***@***.***> wrote:  
 
 


Closed #84.
