### ISSUE TITLE
Issue with connecting AWS MSK kafka broker URL

### ISSUE THREAD

**Issue by joshisagar92** [KxSystems/kafka#85]
**Describe the bug**
I was using kdb kafka wrapper to send data to AWS MSK. When we create broker on AWS MSK it will give the URL. This URL generated by AWS MSK contains "-" in the URL. For e.g **b-1.aws.east-us.awsmks.com** Due to hyphen in URL when we try to pass broker URL in config Q throws error.
**To Reproduce**
Please use any URL which have - in it as a broker url. For e.g
`kfk_cfg:(!)` . flip(  (`metadata.broker.list;`b-1.aws.east-us.awsmks.com:9092);  (`statistics.interval.ms;`10000);  (`queue.buffering.max.ms;`1);  (`fetch.wait.max.ms;`10)  );`

**Expected behavior**
Q should not restrict such URL to be used as Kafka broker URL

**Comment by cmccarthy1** [comment]
As you rightly point out the hyphen is going to be an issue as kdb+ symbols cannot support parsing these out by default i.e.

```
q)`b-1.aws.east-us
'1.aws.eas
  [0]  `b-1.aws.east-us
```
However if you explicitly cast from a string to symbol I think it should work i.e.
```
`$"b-1.aws.east-us"
```

Hope this helps

**Comment by joshisagar92** [comment]
Hi @cmccarthy1 ,

I have tried following variation and it throws error.

![image](https://user-images.githubusercontent.com/38806356/121510067-e1171b80-ca04-11eb-8441-19a53db02270.png)

**Comment by cmccarthy1** [comment]
You need to make the configuration an explicit dictionary, since q evaluates right to left you're getting type/evaluation errors for various reasons. The following should fix the above
```
kfk_cfg:`metadata.broker.list`statistics.interval.ms!(`$"b-1.aws.east.us";`10000)
```
Adding the 'list' syntax `(x;y)` allows each to be evaluated separately (doing the conversion in the first element)

**Comment by cmccarthy1** [comment]
I believe the above should fix the issue you are seeing. If your original problem is still persisting please reopen this issue, otherwise open another issue with an updated description.
