### ISSUE TITLE
Failed to get current position offset

### ISSUE THREAD

**Issue by hungchinchang** [KxSystems/kafka#94]
**Describe the bug**
When using the function kfk.PositionOffsets, it is not returning the current offset on the topic from kafka until kdb have processed the message.

**To Reproduce**
```
/- note we do not commit offset
/- check the current position offset on the topic - which should be 1 because there is 1 message.
.kfk.PositionOffsets[kfk_consumer;`queue;0i]
topic partition offset metadata
-------------------------------
queue 0         -1001  ""      
/- subscribe to the topic and process the message
{[x] .kfk.Subscribe[kfk_consumer;x;enlist .kfk.PARTITION_UA;upd x]} each kfk_consumer_topics;
/- check the current position offset on the topic
.kfk.PositionOffsets[kfk_consumer;`queue;enlist 0i]
topic partition offset metadata
-------------------------------
queue 0         1      ""      

```

**Expected behavior**
The function should be able to provide the current position offset on the topic without having to subscribe/process the message so we can determine where the current offset is on the topic and able to be in replay mode until we catch up to the current message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
 - KDB+ banner information 
 KDB+ 4.1t 2021.11.04 Copyright (C) 1993-2021 Kx Systems
l64/ 8()core 31578MB nion debian 127.0.1.1 EXPIRE 2023.04.16 carta.com DEV TMP #76484
 - Repository version [e.g. 0.1.0]

**Additional context**

**Comment by sshanks-kx** [comment]
Related to: https://github.com/confluentinc/librdkafka/issues/1964

**Comment by hungchinchang** [comment]
@sshanks-kx ok, you may close. thanks.

**Comment by sshanks-kx** [comment]
Will have a look & report back on this issue.
Noted open issue with the call here https://github.com/confluentinc/librdkafka/issues/2588 (mentioned for reference)

**Comment by sshanks-kx** [comment]
Added to v1.6.2

**Comment by hungchinchang** [comment]
> Added to v1.6.2

thanks you may close the ticket.

**Comment by hungchinchang** [comment]
closing
